### ISSUE TITLE
Server won't stop - Fabric

### ISSUE THREAD

**Issue by rutizar22** [Toma1O6/Configuration#10]
Hi. Tried installing addon ExtendedAE for Fabric on versions 1.20.1 and 1.19.2. The server does not stop completely. It stops at the message and does not shut down completel:
[Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved.

Log file attachment.
[latest.log](https://github.com/Toma1O6/Configuration/files/13829463/latest.log)

I have notified the addon developer. I got a reply from him: "well it is casued by [configuration](https://www.curseforge.com/minecraft/mc-mods/configuration) and extendedae is using that mod as config lib".

**Comment by rutizar22** [comment]
Thank you. I informed him. When I hear back from him, I'll get back to you.

**Comment by Toma1O6** [comment]
Hi, I'll check it out

**Comment by Toma1O6** [comment]
1.19 versions have been fixed
- [1.19.2](https://www.curseforge.com/minecraft/mc-mods/configuration/files/5009543)
- [1.19.4](https://www.curseforge.com/minecraft/mc-mods/configuration/files/5009502)

Also there is no Fabric version for 1.20.1, at least not official one
