### ISSUE TITLE
Neoforge?

### ISSUE THREAD

**Issue by screret** [Toma1O6/Configuration#12]
We're using this library for our config file in [GregTechCEu Modern](https://www.curseforge.com/minecraft/mc-mods/gregtechceu-modern) and are planning on using NeoForge 1.21 and up. any chance we could get a neoforge version published?

**Comment by Toma1O6** [comment]
I've been considering starting development on NeoForge, so I will most likely port this too, it will be ported probably within like 2 weeks from now depending on my time

**Comment by screret** [comment]
done.

**Comment by Toma1O6** [comment]
Thank you. I have released it on CurseForge
