### ISSUE TITLE
[FEATURE] add @Configurable.RequireRestart

### ISSUE THREAD

**Issue by DancingSnow0517** [Toma1O6/Configuration#16]
add this to your config option that will show red text in hover tooltip, like "Change this option need restart minecraft to apply"

**Comment by Toma1O6** [comment]
This is planned for upcoming versions along with several other improvements

**Comment by Toma1O6** [comment]
Closing this issue as version 3.0 has been published (CF is still being processed) and can be used for development.

This feature is described within [UpdateRestrictions page](https://github.com/Toma1O6/Configuration/wiki/Update-restrictions)
