### ISSUE TITLE
In neoforge >= 21.0.110-beta, open config screen will crash

### ISSUE THREAD

**Issue by DancingSnow0517** [Toma1O6/Configuration#18]
The log shows no implementation method `createScreen(net.neoforged.fml.ModContainer, net.minecraft.client.gui.screens.Screen)` of interface `net.neoforged.neoforge.client.gui.IConfigScreenFactorynet.neoforged.neoforge.client.gui.IConfigScreenFactory`

crash report here https://pastebin.com/9RDX3sp0

**Comment by Toma1O6** [comment]
Looks like Neoforge 21.0.110 introduced breaking change into how custom config screens are registered, I will publish update as soon as possible

**Comment by Toma1O6** [comment]
I have released version 2.3.1 with fix for Neoforge
