### ISSUE TITLE
color problems

### ISSUE THREAD

**Issue by zaze06** [Toma1O6/Configuration#2]
for the end user thay need to type the color in hex
for mod maker/developer that need to put in the default color in hex and can not use for example ColorUIResource to select a color

I may just not know stuff but I cant find how this is posibel

**Comment by Toma1O6** [comment]
Colors are mostly always typed in hex format so that is going to stay. I might add some sort of color selector into UI for users though.

**Comment by zaze06** [comment]
Thx. yes its normally typed in hax so that's fine
