### ISSUE TITLE
Can you add a gruping system?

### ISSUE THREAD

**Issue by zaze06** [Toma1O6/Configuration#4]
Hi, I wonder if it would be possible to add a grouping system so for display stuff of a mod it can be under one group and so on.
Idk if this is added but I don't see it if so tell me

**Comment by Toma1O6** [comment]
It already exists. Take a look at IConfigWriter#writeObject method. 
Your category must extend ObjectType and provide constructor with IObjectSpec parameter which is then supplied to your object when created. Then inside your category constructor you just call IObjectSpec#getWriter and you can build internal structure with it
