### ISSUE TITLE
Fabric 1.19.4?

### ISSUE THREAD

**Issue by AzureDoom** [Toma1O6/Configuration#6]
Hi! I really like the mod and wanted to switch from Midnight Lib to this, do you have a 1.19.4 Fabric planned at all?

**Comment by Toma1O6** [comment]
Yeah, it is planned. I will probably release it within next week

**Comment by AzureDoom** [comment]
Ah alright! I was just getting ready to send a PR but ok!

**Comment by Toma1O6** [comment]
Okay, Fabric 1.19.4 has just been released to curseforge, it should be available soon
