### ISSUE TITLE
crash on runClient

### ISSUE THREAD

**Issue by 08118651** [Toma1O6/Configuration#9]
I'm making gregtechceu modern affiliated mod, tip under Caused by:
            Java. Lang. ClassNotFoundException: Dev. Toma. Configuration. Config. The format. ConfigFormats,
I add the configuration to dependency, the result error under Caused by:
            javax.net.ssl.SSLHandshakeException: PKIX path building failed:  sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Lastest:
[latest.log](https://github.com/Toma1O6/Configuration/files/13729173/latest.log)

Can you give me some advice?

**Comment by Toma1O6** [comment]
Are you able to open https://raw.githubusercontent.com/Toma1O6/UpdateSchemas/master/configuration-forge.json link on your PC?

**Comment by 08118651** [comment]
@Toma1O6  yes

**Comment by 08118651** [comment]
In addition, when I turned off steamcommunity_302 accelerator, the link above could not open, after runClient, an error was reported:
Caused by: java.net.ConnectException
Caused by: java.nio.channels.UnresolvedAddressException

**Comment by 08118651** [comment]
In addition, when I turned off steamcommunity_302 accelerator, the link above could not open, after runClient, an error was reported:
Caused by: java.net.ConnectException
Caused by: java.nio.channels.UnresolvedAddressException

**Comment by Toma1O6** [comment]
Looks like some problem with website certificates, not really related to my mod and I cannot do anything about it. I am currently getting the same from JEI version check.
